name: Lint & Fix

on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 14
  X12: .0x12-javascript-warm_up

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: | 
            ${{ env.X12 }}

      - name: Install Dependencies
        run: npm install

      - name: Semistandard Test & Fix
        run: npm run semi:fix
