name: Lint & Fix

on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 14
  0X12: /0x12-javascript-warm_up

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.0X12 }}

      - name: Install Dependencies
        run: npm ci
        working-directory: ${{ env.0X12 }}

      - name: Semistandard Test & Fix
        run: npm run semi:fix
        working-directory: ${{ env.0X12 }}
