name: Lint & Fix

on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 14
  X12: 0x12-javascript-warm_up

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        working-directory: ${{ env.X12 }}
        run: npm install

      - name: Semistandard Fix
        working-directory: ${{ env.X12 }}
        run: npm run semi:fix
      
      - name: Standard Fix
        working-directory: ${{ env.X12 }}
        run: npm standard:fix
